- hosts: all
  vars:
    gpu: "no"
  vars_files:
    - vars/users.yml
  tasks:
    - name: learning loops
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - httpd
        - firewalld

    - name: debug vars
      debug:
        msg: User {{ item['name'] }} belongs to group {{ item['group'] }} & UID is set to {{ item['uid'] }}
      with_items:
        - "{{ users }}"

    - name: check postfix service
      command: systemctl is-active postfix
      register: output
      ignore_errors: yes

    - debug:
       var: output

    - name: conditional task
      debug:
        msg: "I executed"
      when:
        - output.rc != 0
        - gpu == "no"
