---
- name: This play demonstrates variables inclusion from file
  hosts: servera.lab.example.com
  tasks:
  - name: debug the variables 
    debug:
      msg: >
        "{{ packages['web_package'] }}     {{ packages['db_package'] }}"

  - name: include variables from vars1.yml
    include_vars: vars/vars1.yml
  
  - name: debug the variables 
    debug:
      msg: >
        "{{ packages['web_package'] }}     {{ packages['db_package'] }}"
